# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go-compile-windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Compile
      run: |
        mkdir -p build/data/configs build/data/exports
        export GOOS=windows
        export GOARCH=amd64
        go build -o build/gboard.exe
        cp .config.json build/
        cp model.config.json build/data/configs/

    - name: Publish
      uses: actions/upload-artifact@v2
      with:
        name: gboard-windows-executable
        path: build/
